apiVersion: v1
kind: Service
metadata:
  name: owlet
  labels:
    app: owlet
spec:
  type: NodePort
  ports:
  - name: owlet
    port: 8080
    nodePort: 30000
  selector:
    app: owlet
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: owlet
  labels:
    app: owlet
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: owlet
    spec:
      imagePullSecrets:
      - name: aliyun-cr
      containers:
      - name: owlet
        image: $IMAGE_NAME
        # command: []
        # args: []
        resources:
          requests:
            cpu: 500m
            memory: 512Mi
        envFrom:
        - configMapRef:
            name: owlet
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: /storage/owlet/assets
          name: data-volume
      volumes:
       - name: data-volume
         hostPath:
           path: /storage/kube-owlet
           type: DirectoryOrCreate
#      - name: data-volume
#        persistentVolumeClaim:
#          claimName: owlet
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: owlet
  # annotations:
  #     nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: owlet
          servicePort: 8080
    host: owlet.xracoon.com
#  - http:
#      paths:
#      - path: /owlet
#        backend:
#          serviceName: owlet
#          servicePort: 8080
#    host: www.xracoon.com
#---
#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: owlet
#spec:
#  accessModes:
#  - ReadWriteOnce
#  resources:
#    requests:
#      storage: "10Gi"