server:
  port: 8080
  servlet:
    context-path: /
  maxHttpHeaderSize: 8192
info:
  info2222: aaaabbbb

app:
  upload.path: file:///storage/owlet/assets/
  asset.server: /assets

mybatis:
  typeAliasesPackage: com.xracoon.sys.owlet.orm.models,com.xracoon.sys.owlet.orm.modelsex
  # config-location: classpath:mybatis-config.xml
  mapperLocations: classpath:mapper/*.xml

spring:
  datasource:
    url: jdbc:mysql://${DB_MASTER_HOST}:${DB_MASTER_PORT:3306}/${DB_MASTER_DATABASE:owlet}?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true
    username: ${DB_MASTER_USER:root}
    password: ${DB_MASTER_PASSWORD}

  jackson:
    serialization:
      indent_output: false
      write_dates_as_timestamps: true
      fail_on_empty_beans: false
    deserialization:
      fail_on_unknown_properties: false
    parser:
      allow_unquoted_control_chars: true
      allow_single_quotes: true

  flyway:
    locations: ["classpath:/db/migration"]

  cache:
    ehcache:
      config: classpath:/ehcache.xml

management:
  endpoints:
    enabled-by-default: false
  endpoint:
    info.enabled: true
    health.enabled: true
