package com.xracoon.sys.owlet.orm.models;

public class SeriesAssign {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column series_assign.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column series_assign.series_id
     *
     * @mbggenerated
     */
    private Long seriesId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column series_assign.article_id
     *
     * @mbggenerated
     */
    private Long articleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column series_assign.order
     *
     * @mbggenerated
     */
    private Integer order;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column series_assign.id
     *
     * @return the value of series_assign.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column series_assign.id
     *
     * @param id the value for series_assign.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column series_assign.series_id
     *
     * @return the value of series_assign.series_id
     *
     * @mbggenerated
     */
    public Long getSeriesId() {
        return seriesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column series_assign.series_id
     *
     * @param seriesId the value for series_assign.series_id
     *
     * @mbggenerated
     */
    public void setSeriesId(Long seriesId) {
        this.seriesId = seriesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column series_assign.article_id
     *
     * @return the value of series_assign.article_id
     *
     * @mbggenerated
     */
    public Long getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column series_assign.article_id
     *
     * @param articleId the value for series_assign.article_id
     *
     * @mbggenerated
     */
    public void setArticleId(Long articleId) {
        this.articleId = articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column series_assign.order
     *
     * @return the value of series_assign.order
     *
     * @mbggenerated
     */
    public Integer getOrder() {
        return order;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column series_assign.order
     *
     * @param order the value for series_assign.order
     *
     * @mbggenerated
     */
    public void setOrder(Integer order) {
        this.order = order;
    }
}