package com.xracoon.sys.owlet.orm.models;

public class TagAssign {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag_assign.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag_assign.res_type
     *
     * @mbggenerated
     */
    private Integer resType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag_assign.res_id
     *
     * @mbggenerated
     */
    private Long resId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag_assign.tag
     *
     * @mbggenerated
     */
    private Integer tag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag_assign.tag_order
     *
     * @mbggenerated
     */
    private Integer tagOrder;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag_assign.id
     *
     * @return the value of tag_assign.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag_assign.id
     *
     * @param id the value for tag_assign.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag_assign.res_type
     *
     * @return the value of tag_assign.res_type
     *
     * @mbggenerated
     */
    public Integer getResType() {
        return resType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag_assign.res_type
     *
     * @param resType the value for tag_assign.res_type
     *
     * @mbggenerated
     */
    public void setResType(Integer resType) {
        this.resType = resType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag_assign.res_id
     *
     * @return the value of tag_assign.res_id
     *
     * @mbggenerated
     */
    public Long getResId() {
        return resId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag_assign.res_id
     *
     * @param resId the value for tag_assign.res_id
     *
     * @mbggenerated
     */
    public void setResId(Long resId) {
        this.resId = resId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag_assign.tag
     *
     * @return the value of tag_assign.tag
     *
     * @mbggenerated
     */
    public Integer getTag() {
        return tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag_assign.tag
     *
     * @param tag the value for tag_assign.tag
     *
     * @mbggenerated
     */
    public void setTag(Integer tag) {
        this.tag = tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag_assign.tag_order
     *
     * @return the value of tag_assign.tag_order
     *
     * @mbggenerated
     */
    public Integer getTagOrder() {
        return tagOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag_assign.tag_order
     *
     * @param tagOrder the value for tag_assign.tag_order
     *
     * @mbggenerated
     */
    public void setTagOrder(Integer tagOrder) {
        this.tagOrder = tagOrder;
    }
}