package com.xracoon.sys.owlet.orm.mappers;

import com.xracoon.sys.owlet.orm.models.DictGroup;
import com.xracoon.sys.owlet.orm.models.DictGroupExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DictGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_group
     *
     * @mbggenerated
     */
    int countByExample(DictGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_group
     *
     * @mbggenerated
     */
    int deleteByExample(DictGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_group
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_group
     *
     * @mbggenerated
     */
    int insert(DictGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_group
     *
     * @mbggenerated
     */
    int insertSelective(DictGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_group
     *
     * @mbggenerated
     */
    List<DictGroup> selectByExample(DictGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_group
     *
     * @mbggenerated
     */
    DictGroup selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_group
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") DictGroup record, @Param("example") DictGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_group
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") DictGroup record, @Param("example") DictGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_group
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DictGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_group
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DictGroup record);
}