package com.xracoon.sys.owlet.orm.mappers;

import com.xracoon.sys.owlet.orm.models.DictItem;
import com.xracoon.sys.owlet.orm.models.DictItemExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DictItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_item
     *
     * @mbggenerated
     */
    int countByExample(DictItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_item
     *
     * @mbggenerated
     */
    int deleteByExample(DictItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_item
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_item
     *
     * @mbggenerated
     */
    int insert(DictItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_item
     *
     * @mbggenerated
     */
    int insertSelective(DictItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_item
     *
     * @mbggenerated
     */
    List<DictItem> selectByExample(DictItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_item
     *
     * @mbggenerated
     */
    DictItem selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_item
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") DictItem record, @Param("example") DictItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_item
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") DictItem record, @Param("example") DictItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_item
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DictItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_item
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DictItem record);
}