package com.xracoon.sys.owlet.orm.mappers;

import com.xracoon.sys.owlet.orm.models.GenericType;
import com.xracoon.sys.owlet.orm.models.GenericTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GenericTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table generic_type
     *
     * @mbggenerated
     */
    int countByExample(GenericTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table generic_type
     *
     * @mbggenerated
     */
    int deleteByExample(GenericTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table generic_type
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table generic_type
     *
     * @mbggenerated
     */
    int insert(GenericType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table generic_type
     *
     * @mbggenerated
     */
    int insertSelective(GenericType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table generic_type
     *
     * @mbggenerated
     */
    List<GenericType> selectByExample(GenericTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table generic_type
     *
     * @mbggenerated
     */
    GenericType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table generic_type
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") GenericType record, @Param("example") GenericTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table generic_type
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") GenericType record, @Param("example") GenericTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table generic_type
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(GenericType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table generic_type
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(GenericType record);
}