package com.xracoon.sys.owlet.orm.mappers;

import com.xracoon.sys.owlet.orm.models.SeriesAssign;
import com.xracoon.sys.owlet.orm.models.SeriesAssignExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SeriesAssignMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table series_assign
     *
     * @mbggenerated
     */
    int countByExample(SeriesAssignExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table series_assign
     *
     * @mbggenerated
     */
    int deleteByExample(SeriesAssignExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table series_assign
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table series_assign
     *
     * @mbggenerated
     */
    int insert(SeriesAssign record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table series_assign
     *
     * @mbggenerated
     */
    int insertSelective(SeriesAssign record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table series_assign
     *
     * @mbggenerated
     */
    List<SeriesAssign> selectByExample(SeriesAssignExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table series_assign
     *
     * @mbggenerated
     */
    SeriesAssign selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table series_assign
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SeriesAssign record, @Param("example") SeriesAssignExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table series_assign
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SeriesAssign record, @Param("example") SeriesAssignExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table series_assign
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SeriesAssign record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table series_assign
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SeriesAssign record);
}