package com.xracoon.sys.owlet.orm.mappers;

import com.xracoon.sys.owlet.orm.models.TagAssign;
import com.xracoon.sys.owlet.orm.models.TagAssignExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TagAssignMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_assign
     *
     * @mbggenerated
     */
    int countByExample(TagAssignExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_assign
     *
     * @mbggenerated
     */
    int deleteByExample(TagAssignExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_assign
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_assign
     *
     * @mbggenerated
     */
    int insert(TagAssign record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_assign
     *
     * @mbggenerated
     */
    int insertSelective(TagAssign record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_assign
     *
     * @mbggenerated
     */
    List<TagAssign> selectByExample(TagAssignExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_assign
     *
     * @mbggenerated
     */
    TagAssign selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_assign
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TagAssign record, @Param("example") TagAssignExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_assign
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TagAssign record, @Param("example") TagAssignExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_assign
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TagAssign record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_assign
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TagAssign record);
}