package com.xracoon.sys.owlet.orm.mappers;

import com.xracoon.sys.owlet.orm.models.UserIdentity;
import com.xracoon.sys.owlet.orm.models.UserIdentityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserIdentityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_identity
     *
     * @mbggenerated
     */
    int countByExample(UserIdentityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_identity
     *
     * @mbggenerated
     */
    int deleteByExample(UserIdentityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_identity
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_identity
     *
     * @mbggenerated
     */
    int insert(UserIdentity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_identity
     *
     * @mbggenerated
     */
    int insertSelective(UserIdentity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_identity
     *
     * @mbggenerated
     */
    List<UserIdentity> selectByExample(UserIdentityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_identity
     *
     * @mbggenerated
     */
    UserIdentity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_identity
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") UserIdentity record, @Param("example") UserIdentityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_identity
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") UserIdentity record, @Param("example") UserIdentityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_identity
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserIdentity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_identity
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserIdentity record);
}